### ISSUE TITLE
windowsでのプログラム実行方法について

### ISSUE THREAD

**Issue by sanoP1man** [pymee/studygroup#10]
windows環境でpythonプログラムを実行する方法について、シンプルなやり方を確認、検討する。
@kotarouikedaさん確認お願いします！

---
+ 現状の認識
py hoge.py で実行する場合、python2が実行される可能性がある。
これを避けるにはシェバンが必要。
windowsユーザーだけシェバン記載で、pyで実行する？
python3で実行する場合、環境変数の変更が必要。環境変数を変えるのは大変という問題がある。。。

**Comment by sanoP1man** [comment]
https://www.python.jp/install/windows/install_py3.html
windows版のpythonインストール方法をみると、「"Add Python 3.x to PATH" 」という、項目があるみたいとで、パスの追加が簡単かもしれません。
path追加の方が簡単かもしれません。

**Comment by kotarouikeda** [comment]
勉強会通知メールに「Windowsユーザーはインストール時に"Add Python 3.x to PATH" のチェックを入れてインストールしてください」と記載するのもアリですかね。

**Comment by kotarouikeda** [comment]
あるいは単純に資料の「python3」の箇所を「py」に読み替えて貰うのはどうでしょう。
「py ファイル名.py」で実行できますし。

今の私の環境はpython2と3が入っていてどちらもパスが通っていない状態ですが、何も指定しないとpython3の方が起動します。
pythonのドキュメントにも「最新のバージョンが起動する」との記載がありました。

https://docs.python.jp/3/using/windows.html

**Comment by sanoP1man** [comment]
最新のが実行されるのってシェバン抜いても最新のが実行されるということですかー？
であれば、基本はパスを通してもらう形で、ダメな場合はpy hoge.pyはどうですか？
資料にはwindows用の説明を追記する形で。。。

**Comment by kotarouikeda** [comment]
シェバン書いてないソースを実行してみたら最新のpythonで実行されました。というか「py」だけで実行すると対話モードで起動するのですが、それも態々引数で指定しない限り最新のバージョンで起動されていました。

また、試しにパス通してみたら「python3 ファイル名.py」ではなく「python ファイル名.py」の形になりました。
実行ファイル名がpython.exeなんでこんな形になってしまいます。
パス通しても差分が出てしまうならもう最初から読み替えでいいのでは？と思います。

**Comment by sanoP1man** [comment]
色々試していただきありがとうございます！
ですね、パス通しても差分でるのであれば、パスのチェックはあえてつけないでインストールしてもらいますか。

ただ、既にインストールしてた人とか、間違ってパスありでインストールした人も出てきそうなんで、説明スライドに追加しときます！

**Comment by kotarouikeda** [comment]
そうですね。下手に環境変数汚すこともないでしょうし。
対応ありがとうございます。勉強会当日は私もうろつきながらフォローできればと思います。
