### ISSUE TITLE
ifの対話モードについて

### ISSUE THREAD

**Issue by sanoP1man** [pymee/studygroup#11]
reviewで下記意見があったのでissueにしました！
ifの部分ですが確かに、インデントを打つのは辛いなと思いました。
なので、おみくじプログラム改良後、テスト用のコードを追加して動作確認という流れで問題ないでしょうか？
他に、いいやり方あれば教えてください！

---
@JinKanai
対話モードでifのようなインデント入るのやるのは結構大変かも！です。
printの前にタブを押すことを説明しないと大変なことに・・・！？

@sanoP1man
確かに、、、下記のような形はどうでしょうか。
ifの場合は、インタプリタの実行やめて

1. コードをひとまず完成させる
1. 一度動作を確認
1. ifの前にprint("数字：+ num)を記載
1. 何回か実行して数字と結果の比較をしてもらう

**Comment by JinKanai** [comment]
私はそれでいいと思います～

**Comment by sanoP1man** [comment]
ありがとうございます！ひとまず、こちらで修正します！
資料修正後クローズします！
