### ISSUE TITLE
第2回以降の開催内容

### ISSUE THREAD

**Issue by JinKanai** [pymee/studygroup#12]
ちょっと気が早いですが、第2回以降の内容のアイデアを忘れないうちメモしときます。ただの私のメモなので、採用するしないは今後ここで議論できればと思います～

第2回は、ファイルと他なにかやりましょうか。
多分、ファイル化するだけだと1時間もかからないので・・・

- ファイル入出力
    - CSVとjsonを扱わせる。CSVはリスト、jsonは辞書からの使い勝手がいいことを強調。余裕がありそうならansibleなどで必須のYAMLの使い方も。
- 仮想環境
    - venv的な仮想環境の考え方と使い方をやる。python標準のvenvがいいと思う（pyenvはバージョン変えられて便利だけど、かなり強引な方法をとっているらしく、商用では利用ケース少ないかと）
- pipの使い方
    - 仮想環境とあわせて。pip freeze > requirements.txt ～ python -m venv VENVNEAME ～ pip install -r requirements.txt の流れでできればいいかと。
- データベース
    - SQlite3が使えればいいかな・・・
- クラス
    - 商用でやるならクラスの知識は必須。あとフレームワークもクラス、というかオブジェクト指向を知らないと使えないので、必須事項かな。
    - オブジェクト指向は、考え方のレクチャをゆる勉で９月中に実施予定です。

**Comment by JinKanai** [comment]
アンケーとみるとモジュールの人気が高かったので、
- モジュールの扱い方
    - モジュール化のやりかた
    - 組み込みモジュールの使い方
    - 外部モジュールの使い方
pipと一緒にやるのがいいでしょうね

**Comment by kotarouikeda** [comment]
①
- 仮想環境
- pipの使い方 
  - venvで隔離環境を作って、そこへpipで必要なパッケージを集めていくイメージですかね？
開発環境を作る上でも有用なので是非覚えておきたい所ですが・・・

②
- ファイル入出力
  - txt/csv/jsonとやりたいですね。入力元の書式が不定形で整形する事が一番多いと思うので、txtを整形する内容を入れてもいいと思います。

③
- モジュールの扱い方 
- クラス 
  - この2つは開発する上で必須になりますので、私も一票入れたいです。

②③は必須で、①はちょっと優先度低いかなと思います。
DBは3回目でガッツリやりたいですね。
今出ている以外だとエラーと例外なんかも入れたいですね。

**Comment by JinKanai** [comment]
@kotarouikeda コメントありがとうです！
仮想環境は必須な気がしてきました。不用意にpipでパッケージ入れると既存のアプリが動かなくなったりすることがあるので、そういうのを避けるための知識として。。

ファイルについて、独自フォーマットのファイル扱いもあったほうがいいですね。テキストをパースさせる力をつけてもらうという観点で。

しかし、こうして拾っていくと2時間じゃ全然足りないですね。
月イチペースで、講師を交代してやっていけるといいんですけどね・・・

**Comment by sanoP1man** [comment]
前回の勉強会はlistのところまでしかできてないので、下記内容プラス何かの方がいいと思いました！

- 前回のおさらい
- 辞書
- 辞書とリストの入れ子

ファイルの入出力は是非したいので、forによるlist, dicの取り出し、whileも必要になりそうかなと思います。

クラス、モジュールはやった方がいいと思います！
仮想環境はこれを機にしっかり勉強会したいです。
ただ、これらの内容を２回目にいれるとまた時間が足りなくなりそうな気がします。もう一回講義増やしたいですねー

**Comment by kotarouikeda** [comment]
@JinKanai @sanoP1man 
クラス/モジュール/pip/venv辺りはセットでやっておかないといけなさそうですねぇ。
おさらい/辞書/入れ子+ファイルIO+上記のセットだとまた尻切れトンボになりそう…組み合わせをミーティングで議論してみましょう。

例外処理もpythonに限らずどんなプログラムを作るに当たっても入れておかないといけないので、是非2回目の内容に入れたいです。

**Comment by sanoP1man** [comment]
二回目の勉強会が終了したのでクローズします。
