### ISSUE TITLE
フローチャート（廣川、浦野さん作成）レビュー

### ISSUE THREAD

**Issue by HIROSEKAN** [pymee/studygroup#14]
各章に追加するフローチャートのレビューをお願いいたします！
[フローチャート_3章～9章.pptx](https://github.com/pymee/studygroup/files/2422548/_3.9.pptx)

パワポの最後に検討事項も書きましたので、皆さんの意見を聞きたいです。
よろしくお願いいたします！

**Comment by sanoP1man** [comment]
レビューが遅くなってすみません、内容確認しました。
細かい部分も指摘したので指摘点が多くなってしまいました、、、
すみませんが確認をお願いします。

---
# スライドの最後の確認事項について

+ 完成コードのページ以外（インタプリタ操作など）にも、フローチャートを入れるか?
インタプリタ操作は動作確認の意味が強いのでフローチャートは入れない方がいいと思います。
(折角いろんな部分のフローチャートを作って頂いたのにすみません。。。)
ただし、条件分岐に関しては説明の部分でフローチャートを入れた方がわかりやすいと思うので、「条件分岐」スライドの次のページに下記ふろーのフローチャートを差し込んだ方がいいかなと。

> if 条件1:
>     処理1
> elif 条件2:
>     処理2-1
>     処理2-2
> else:
>     処理3

+ 章ごとの全体フローチャートを、資料に盛り込むか?
章ごとの全体フローチャートを資料に盛り込んだ方がいいかなと思います。
なので、スライドは下記のような順番になる想定です。

1. フローチャートの図
2. コードの修正前後の比較資料
3．フローチャートとコードの説明資料
---

# パワーポイントの資料についての指摘点は下記の通りです。

+ 出力の部分について(全体)
フローチャートの中に「小栗(name)さんの運勢は、大吉　すべてよし(omikuji_1)です！と出力」と記載すると
print("小栗(name)さんの運勢は、大吉　すべてよし(omikuji_1)です！")のことになるので、
nameさんの運勢はunseiです!と出力 にして変数はそのまま残す形のほうがいいと思いました。


+ スライド11,13,14,15,19,21,
> ランダムに選択した数字を num に代入(0～5) 
「ランダムに選択した数字を num に代入(0～4)」に修正をお願いします。
すみません、コード自体をrandom.randrange(0,5)に修正する必要があるので、フローチャートも合わせて修正お願いします。

+ スライド20,21,(32,36も同じです)
> num をもとに、unsei に omikuji の一部を代入

omikujiの一部ではなく、omikujiの要素を代入のほうがいいかと思いました。

+ スライド24,25
> ランダムに選択した数字をもとに、unsei に omikuji の一部を代入

「リストからランダムに要素を選択し、unseiに選択した要素を代入する」に修正をお願いします。
ランダムに選択した数字ではなく、リストの要素自体をランダムに選択しているので～

+ スライド28
> ランダムに選択した数字をもとに、unsei_key に omikuji の一部を代入

下記3つの処理を行っているので処理を3つに分けて書いた方がいいかなと思いました。

1. 辞書omikujiのカギのみを出力
1. 出力した鍵をリストに変換
1. 変換したリストからランダムに要素を選択し代入

+ スライド32,34,36
> ランダムに選択した数字をもとに、unsei に omikuji の一部を代入

リストomikujiからランダムで要素を選択しunseiに代入　に修正をお願いします。


+ スライド35
> unsei に 吉 が含まれる

unsei['all']に'吉'が含まれる　に修正をお願いします。
unseiだとリストomikujiから選択された辞書をさすことになります。
実際のコードでは、辞書unseiの鍵が「'all'」の値に'吉'が含まれているか確認しているので、プログラムとフローチャートの流れが異なってきます。

**Comment by sanoP1man** [comment]
すみません、コメントを一部修正させてください。。。

+ 訂正前
+ スライド11,13,14,15,19,21,
> ランダムに選択した数字を num に代入(0～5) 
「ランダムに選択した数字を num に代入(0～4)」に修正をお願いします。
すみません、コード自体をrandom.randrange(0,5)に修正する必要があるので、フローチャートも合わせて修正お願いします。


+ 訂正後
+ スライド19,21,
> ランダムに選択した数字を num に代入(0～5) 
「ランダムに選択した数字を num に代入(0～4)」に修正をお願いします。

**Comment by HIROSEKAN** [comment]
確認ありがとうございます。
佐野さんから頂いた指摘を修正しました！

また、それぞれの章のフローチャート一覧や完成コードで、枠に収まるように修正してみました。
ただ、どうしても5章のフローチャートはどうしても大きくなってしまいます。（if文が多いので）
何かいい方法ありますかね。。。
[フローチャート_3章～9章_ver2.pptx](https://github.com/pymee/studygroup/files/2441233/_3.9._ver2.pptx)

**Comment by sanoP1man** [comment]
修正ありがとうございます！
内容確認します！

ifはどうしても条件が多いですからね、、、
なにかいい案あったら連絡します！

**Comment by JinKanai** [comment]
最近見れてなくてすみません。
すでに↓会話済みなら申し訳ないです。

全体的に、紙面と記載内容のサイズがあってないと思うんですが、これって誰かが発表用に整形してくれるんでしたっけ？多分プロジェクタに写すと見えないです。。。

elifを使うと横に長くなるのはしょうがないっすね。関数に出して早期リターンさせるのがよいのですが、今回そこまでやんないですからねえ
１～３までは省略とかしたら見にくいですかね。

@HIROSEKAN 
issueやプルリク上げるときは、assignieeにメンバーを設定したほうがよいです。
設定しておきました

**Comment by HIROSEKAN** [comment]
@JinKanai 
ご確認、ご指摘ありがとうございます。
git使いこなせずすみません、、、勉強になります。

**Comment by nakayama-akio** [comment]
確認遅くなりすみません。
「フローチャート_3章～9章_ver2.pptx」にて以下を確認しました。

・スライド12,13
　現在　：numをもとに、unseiにomikujiの要素を代入
　変更案：omikujiのnumの位置にある要素をunseiに代入
　　→１つ前のフローでnumにランダムの数字を代入としているので
　　　配列:omikujiの添え字としてnumを利用していることを
　　　明示して記載しました。

・スライド20,21
　現在　：変換したリストからランダムに要素を選択し、代入
　変更案：変換したリストからランダムに要素を選択し、unsei_keyに代入
　　　　→代入先の変数名を追加

よろしくお願いします。

**Comment by shungurio** [comment]
みなさま　遅くにお疲れ様です。
フローチャートがあって、わかりやすくプログラミングらしく、
楽しめる資料でいいと思います。
技術的な指摘はできませんが、きになったのは1点だけ。

各章の冒頭に、なにを学んだのかポイントをあとで参照できるといいと思います。
4章 名前を入力しよう（リスト？）
7章違う方法でやってみよう（辞書）など
6章②もっと短くしよう！（choiceに変更）を見てそう思いました。
P.19 chukihi 誤字です。

他は、特に大きな修正はありません。

**Comment by sanoP1man** [comment]
@shungurio 
つくってもらった資料は私がいま作ってる勉強会資料にマージしようのと思ってます。
イメージとしては、各章の完成コードの次スライドに差し込むかたちです。
なので、何を学んだかのポイントは勉強会資料でカバーできるので、追加はいらないかなと思います。

**Comment by HIROSEKAN** [comment]
@nakayama-akio 
確認ありがとうございます。
修正してみました。
@shungurio 
誤字の発見ありがとうございます。（気が付かなかった・・・）
@sanoP1man 
勉強会資料の上記誤字の修正、お願い致します。7章の完成コードの部分です！

[フローチャート_3章～9章_ver3.pptx](https://github.com/pymee/studygroup/files/2448544/_3.9._ver3.pptx)

**Comment by sanoP1man** [comment]
@HIROSEKAN 修正しました！フローチャートの修正ありがとうございます。

**Comment by sanoP1man** [comment]
資料へのマージも完了したのでクローズします。
