### ISSUE TITLE
アルゴリズムとフローチャート.pptx　レビュー

### ISSUE THREAD

**Issue by JinKanai** [pymee/studygroup#2]
中山さん作成「アルゴリズムとフローチャート.pptx」のレビューはこちらで。

ページ数
指摘内容

のフォーマットでお願いします。

**Comment by JinKanai** [comment]
3ページ
料理に例えるのは難しい気がする・・・プログラミング言語は、包丁というよりは「低級言語がかまどと薪、高級言語がフルオートのグリル付きシステムキッチン」とかか・・？
あと、bashは言語ではないので無難にjavaなんかでよいと思います。

7ページなど
繰り返しの文法にpython以外の言語を持ってくるのはよくないかな。開始値、境界、増減値を記載するならそのまま日本語のほうがよいかも・・

**Comment by uranos0601** [comment]
3ページ
ネットとかの説明だと料理に例えているものが多いみたいです。。
言語がでてくるからややこしくなっているだけで
料理で貫くのであれば
プログラム(料理)
アルゴリズム(レシピ)
のほうが簡潔でわかりやすいのではないでしょうか

**Comment by nakayama-akio** [comment]
レビューありがとうございます。
現在までの指摘点を修正した資料を
Tocaroにアップロードしました。
※同名ファイルです。

3ページ
例えが悪いと余計混乱するので、
料理の文言は混乱するので削除しました。

7ページなど
繰り返しを日本語に修正しました。

**Comment by sanoP1man** [comment]
レビュー遅くなってすみません！
作成ありがとうございます！

ページ３以降(項番２)
ページ３でいろんなフローチャートを紹介しているので、その後に各図形の説明のスライドをいれた方がいいかなと思いました。

四角は条件分岐の処理で、変数を代入するや足し算したりする
ひし形は条件処理で、条件を書いて判断する
開始と終了があるみたいな形で。

その説明をした後に、各フローチャートの説明をした方が分かりやすいかなと思います。
実際は、やりたいこと→フローチャート→プログラム作成なので、この３つのことを横に並べて説明すると流れもわかっていいかなと。

順次処理の場合は、、、

+ やりたいこと
変数に文字を代入して、printしたい

+ フローチャートにすると
フローチャートの図

+ プログラム
プログラムの内容

**Comment by nakayama-akio** [comment]
レビューありがとうございます。
上記指摘を反映した資料を再アップロード
しました。

**Comment by sanoP1man** [comment]
資料作成ありがとうございます。
修正等がなければこちらクローズします。

**Comment by JinKanai** [comment]
こちらクローズします〜
