### ISSUE TITLE
資料のshebangについて認識があっているか確認

### ISSUE THREAD

**Issue by sanoP1man** [pymee/studygroup#8]
作成した資料のshebangについて認識があっているか確認させて下さい。
それと、pythonのプログラムですがpython hogehoge.pyで実行するやり方と、./hogehoge.pyで実行するやり方、どちらが汎用的なのか確認させて下さい。

**Comment by kotarouikeda** [comment]
windowsでもPython2と3が入っている際にPython3の指定になるみたいです
参考：http://d.hatena.ne.jp/yohhoy/20150320/p1
　　　　https://docs.python.jp/3/using/windows.html(3.4.1.3. スクリプトから起動する)

**Comment by JinKanai** [comment]
シェバンの話しだしたの確か私なんですが、無にしましょうか。
最初のうちは、python3 xxx.pyで明示的に実行したほうがわかりやすいのかなと思ったり。

windowsは、デフォルトだとpythonにpathが通ってないみたいなんで、py xxx.pyになるかな。
-  pathを通してもらうか、
- py.exeで実行する手順を追加するか、
- windows参加禁止にするかｗ
上記、資料で検討しないとですね・・・

**Comment by sanoP1man** [comment]
シェバンは今回の説明では入れない。
対象が初心者で、はじめからシェバンの話をするのは難しい。

実行権限変えて、./で実行する形は、別のタイミング(四回目とかで)でやった方がいい。

実行は下記コマンドで統一
python3　hogehoge.py

windowsはシンプルなやり方について、@korarouikedaさんの方で確認してもらう。こちらは、別issueで管理。

勉強会コードからシェバン部分を削除する(@kotarouikeda)、修正確認後クローズ。

---
sanoめも
windowsで、py hoge.py で実行すると
python2が実行される可能性がある、これを避けるならシェバンが必要
windowsで、python3で実行する場合、環境変数の変更が必要。

**Comment by kotarouikeda** [comment]
01_print.py～07_if_in.pyのシェバン表記を削除しました。確認の上問題が無ければissueをクローズして下さい。

**Comment by sanoP1man** [comment]
修正確認しました。こちらクローズします。
