### ISSUE TITLE
文字コードの宣言について

### ISSUE THREAD

**Issue by sanoP1man** [pymee/studygroup#9]
デフォルトと同じ文字コードを使用する場合(python3だとデフォルトUTF-8)、記載が非推奨でした。。、
こちら勉強会のコードも修正するかどうか確認させて下さい。
+ 参考URL
http://pep8-ja.readthedocs.io/ja/latest/#id12
> ASCII (Python 2) や UTF-8 (Python 3) を使用しているファイルにはエンコーディング宣言を入れるべきではありません。

**Comment by kotarouikeda** [comment]
最初にHelloworldのソースコードを書いた時、そのまま実行すると文字化けを起こしたので文字コードを表記しました。しかし、今そこの表記を消して実行するとちゃんと表示されました。
ファイルの文字コードを確認したらUTF-8になっていたので、.pyのテキストファイルがちゃんとUTF-8の文字コードになっていれば問題なさそうですかね。

**Comment by JinKanai** [comment]
エンコード表記はなくしましょう（私が書いたほうがいいと言ったかもしれないです、すみません）
実行するターミナルとpythonコードの保存時のエンコードがUTF-8になってればあまり考慮しなくていいと思います。

**Comment by JinKanai** [comment]
windowsのコマンドプロンプトだと、coding: shift_jis入れないと日本語はprintすらできないっすね・・・
cmd.exeでサクラエディタとか使う人は、明示的にUTF-8で保存してもらわないとですね。

**Comment by sanoP1man** [comment]
エンコードは記載なしにする。
プログラムファイルの保存時に文字コードをutf-8で保存するように教える。

文字コード部分を勉強会コードから削除し(@kotarouikeda)、確認後クローズ。

**Comment by kotarouikeda** [comment]
01_print.py～07_if_in.pyの文字コード表記を削除しました。確認の上問題が無ければissueをクローズして下さい。

**Comment by sanoP1man** [comment]
修正確認しました！クローズします。
